# Generated by Django 5.2.15 on 2026-06-13 14:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("title", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_holidays",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["organization", "date", "is_active"],
                        name="organizatio_organiz_92c636_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "date"),
                        name="unique_holiday_date_per_organization",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TimeOff",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_at", models.DateTimeField(db_index=True)),
                ("end_at", models.DateTimeField(db_index=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_offs",
                        to="providers.providerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "provider_time_offs",
                "ordering": ["-start_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "start_at", "end_at"],
                        name="provider_ti_provide_a4bdc4_idx",
                    ),
                    models.Index(
                        fields=["provider", "is_active"],
                        name="provider_ti_provide_4daddf_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_at__gt", models.F("start_at"))),
                        name="time_off_end_at_after_start_at",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkingHour",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        db_index=True,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="providers.providerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "provider_working_hours",
                "ordering": ["weekday", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["provider", "weekday", "is_active"],
                        name="provider_wo_provide_6950a9_idx",
                    ),
                    models.Index(
                        fields=["weekday", "start_time", "end_time"],
                        name="provider_wo_weekday_ba8154_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_time__gt", models.F("start_time"))),
                        name="working_hour_end_time_after_start_time",
                    )
                ],
            },
        ),
    ]
