# Generated by Django 5.2.15 on 2026-06-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
