# Generated by Django 5.2.15 on 2026-09-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='providerprofile',
            name='provider_pr_special_9750d4_idx',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='specialty',
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='providers', to='categories.category'),
        ),
    ]
