# Generated by Django 5.2.15 on 2026-06-16 17:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("appointment_created", "Appointment Created"),
                            ("appointment_cancelled", "Appointment Cancelled"),
                            (
                                "appointment_status_changed",
                                "Appointment Status Changed",
                            ),
                            ("payment_initiated", "Payment Initiated"),
                            ("payment_paid", "Payment Paid"),
                            ("payment_failed", "Payment Failed"),
                            ("payment_cancelled", "Payment Cancelled"),
                            ("payment_refunded", "Payment Refunded"),
                            ("working_hour_created", "Working Hour Created"),
                            ("working_hour_updated", "Working Hour Updated"),
                            ("time_off_created", "Time Off Created"),
                            ("time_off_updated", "Time Off Updated"),
                            ("holiday_created", "Holiday Created"),
                            ("holiday_updated", "Holiday Updated"),
                        ],
                        db_index=True,
                        max_length=80,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        db_index=True,
                        default="success",
                        max_length=30,
                    ),
                ),
                ("target_object_type", models.CharField(db_index=True, max_length=100)),
                (
                    "target_object_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("target_object_repr", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="audit_logs_actor_i_3b0e80_idx",
                    ),
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="audit_logs_organiz_86ff70_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="audit_logs_action_bcaa71_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="audit_logs_status_e87055_idx",
                    ),
                    models.Index(
                        fields=["target_object_type", "target_object_id"],
                        name="audit_logs_target__472197_idx",
                    ),
                ],
            },
        ),
    ]
