# Generated by Django 5.2.15 on 2026-06-13 15:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("offerings", "0001_initial"),
        ("organizations", "0001_initial"),
        ("providers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_at", models.DateTimeField(db_index=True)),
                ("end_at", models.DateTimeField(db_index=True)),
                ("blocked_start_at", models.DateTimeField(db_index=True)),
                ("blocked_end_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled_by_customer", "Cancelled by customer"),
                            ("cancelled_by_provider", "Cancelled by provider"),
                            ("completed", "Completed"),
                            ("no_show", "No show"),
                        ],
                        db_index=True,
                        default="confirmed",
                        max_length=32,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                ("cancel_reason", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="organizations.branch",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="offerings.offering",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="providers.providerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "appointments",
                "ordering": ["-start_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "start_at"],
                        name="appointment_custome_ae6671_idx",
                    ),
                    models.Index(
                        fields=["provider", "start_at", "end_at"],
                        name="appointment_provide_128273_idx",
                    ),
                    models.Index(
                        fields=["provider", "blocked_start_at", "blocked_end_at"],
                        name="appointment_provide_1edaff_idx",
                    ),
                    models.Index(
                        fields=["organization", "status"],
                        name="appointment_organiz_d34654_idx",
                    ),
                    models.Index(
                        fields=["status", "start_at"],
                        name="appointment_status_971119_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_at__gt", models.F("start_at"))),
                        name="appointment_end_at_after_start_at",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("blocked_end_at__gt", models.F("blocked_start_at"))
                        ),
                        name="appointment_blocked_end_after_blocked_start",
                    ),
                ],
            },
        ),
    ]
