# Generated by Django 5.2.15 on 2026-06-16 14:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentReminder",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("reminder_24h", "Reminder 24 hours before appointment")
                        ],
                        max_length=40,
                    ),
                ),
                ("channel", models.CharField(max_length=30)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "db_table": "appointment_reminders",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["appointment", "reminder_type"],
                        name="appointment_appoint_ac378c_idx",
                    ),
                    models.Index(
                        fields=["channel", "sent_at"],
                        name="appointment_channel_945111_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("appointment", "reminder_type", "channel"),
                        name="unique_appointment_reminder_per_channel",
                    )
                ],
            },
        ),
    ]
