# Generated by Django 5.2.15 on 2026-06-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointmentreminder"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="appointmentreminder",
            name="appointment_appoint_ac378c_idx",
        ),
    ]
