# Generated by Django 5.2.15 on 2026-09-16 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_appointmentreminder_appointment_appoint_ac378c_idx'),
        ('offerings', '0002_offering_category_and_more'),
        ('organizations', '0001_initial'),
        ('providers', '0002_remove_providerprofile_provider_pr_special_9750d4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visit_mode',
            field=models.CharField(choices=[('in_person', 'In Person'), ('online_chat', 'Online Chat')], db_index=True, default='in_person', max_length=32),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['visit_mode'], name='appointment_visit_m_b708b1_idx'),
        ),
    ]
