# Generated by Django 5.2.15 on 2026-09-17 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_visit_mode_and_more'),
        ('chat', '0002_remove_conversation_unique_active_conversation_per_pair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='chat.conversation'),
        ),
    ]
