# Generated by Django 5.2.15 on 2026-06-11 17:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offering",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("duration_minutes", models.PositiveSmallIntegerField(default=30)),
                ("buffer_before_minutes", models.PositiveSmallIntegerField(default=0)),
                ("buffer_after_minutes", models.PositiveSmallIntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("requires_approval", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offerings",
                        to="organizations.organization",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offerings",
                        to="providers.providerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "offerings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "is_active"],
                        name="offerings_organiz_7d97f8_idx",
                    ),
                    models.Index(
                        fields=["provider", "is_active"],
                        name="offerings_provide_c969e4_idx",
                    ),
                    models.Index(fields=["title"], name="offerings_title_ecb8d1_idx"),
                    models.Index(fields=["price"], name="offerings_price_1a7e0c_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "title"),
                        name="unique_offering_title_per_provider",
                    )
                ],
            },
        ),
    ]
