# Generated by Django 5.2.15 on 2026-07-04 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('offerings', '0001_initial'),
        ('organizations', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='categories.category'),
        ),
        migrations.AddIndex(
            model_name='offering',
            index=models.Index(fields=['category'], name='offerings_categor_38344c_idx'),
        ),
    ]
