# Generated by Django 5.2.15 on 2026-09-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('offerings', '0002_offering_category_and_more'),
        ('organizations', '0001_initial'),
        ('providers', '0002_remove_providerprofile_provider_pr_special_9750d4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='visit_mode',
            field=models.CharField(choices=[('in_person', 'In Person'), ('online_chat', 'Online Chat')], db_index=True, default='in_person', max_length=32),
        ),
        migrations.AddIndex(
            model_name='offering',
            index=models.Index(fields=['visit_mode'], name='offerings_visit_m_593281_idx'),
        ),
    ]
