# Generated by Django 5.2.15 on 2026-09-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_color_remove_category_icon_and_more'),
        ('offerings', '0003_offering_visit_mode_and_more'),
        ('organizations', '0001_initial'),
        ('providers', '0002_remove_providerprofile_provider_pr_special_9750d4_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='offering',
            name='offerings_categor_38344c_idx',
        ),
        migrations.RenameField(
            model_name='offering',
            old_name='category',
            new_name='specialty',
        ),
        migrations.AddIndex(
            model_name='offering',
            index=models.Index(fields=['specialty'], name='offerings_special_0d335b_idx'),
        ),
    ]
