# Generated by Django 5.2.15 on 2026-06-09 17:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=140, unique=True),
                ),
                ("description", models.TextField(blank=True)),
                ("phone_number", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("timezone", models.CharField(default="Asia/Tehran", max_length=64)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "organizations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True)),
                ("phone_number", models.CharField(blank=True, max_length=30)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_branches",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["owner", "-created_at"], name="organizatio_owner_i_059ce6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["is_active", "-created_at"],
                name="organizatio_is_acti_536e89_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["slug"], name="organizatio_slug_5b8b37_idx"),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["organization", "is_active"],
                name="organizatio_organiz_ef28f4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["organization", "name"], name="organizatio_organiz_d1db87_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"),
                name="unique_branch_name_per_organization",
            ),
        ),
    ]
