# Generated by Django 5.2.15 on 2026-06-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="related_object_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
