# Generated by Django 5.2.15 on 2026-06-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_related_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="related_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
