# Generated by Django 5.2.15 on 2026-06-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_alter_notification_related_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("password_changed", "Password Changed"),
                    ("password_reset_requested", "Password Reset Requested"),
                    ("appointment_created", "Appointment Created"),
                    ("appointment_confirmed", "Appointment Confirmed"),
                    ("appointment_cancelled", "Appointment Cancelled"),
                    ("appointment_rescheduled", "Appointment Rescheduled"),
                    ("appointment_reminder", "Appointment Reminder"),
                    ("appointment_completed", "Appointment Completed"),
                    ("appointment_no_show", "Appointment No Show"),
                    ("payment_success", "Payment Success"),
                    ("payment_failed", "Payment Failed"),
                    ("refund_success", "Refund Success"),
                ],
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="notificationdelivery",
            name="type",
            field=models.CharField(
                choices=[
                    ("password_changed", "Password Changed"),
                    ("password_reset_requested", "Password Reset Requested"),
                    ("appointment_created", "Appointment Created"),
                    ("appointment_confirmed", "Appointment Confirmed"),
                    ("appointment_cancelled", "Appointment Cancelled"),
                    ("appointment_rescheduled", "Appointment Rescheduled"),
                    ("appointment_reminder", "Appointment Reminder"),
                    ("appointment_completed", "Appointment Completed"),
                    ("appointment_no_show", "Appointment No Show"),
                    ("payment_success", "Payment Success"),
                    ("payment_failed", "Payment Failed"),
                    ("refund_success", "Refund Success"),
                ],
                max_length=80,
            ),
        ),
    ]
