# Generated by Django 5.2.15 on 2026-07-04 06:37

import apps.notifications.models.notifications
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.JSONField(default=dict, encoder=apps.notifications.models.notifications.UUIDEncoder),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='data',
            field=models.JSONField(blank=True, default=dict, encoder=apps.notifications.models.notifications.UUIDEncoder),
        ),
    ]
