# Generated by Django 5.2.15 on 2026-09-18 17:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('password_changed', 'Password Changed'), ('password_reset_requested', 'Password Reset Requested'), ('appointment_created', 'Appointment Created'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_rescheduled', 'Appointment Rescheduled'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_completed', 'Appointment Completed'), ('appointment_no_show', 'Appointment No Show'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('refund_success', 'Refund Success'), ('chat_message_received', 'Chat Message Received')], max_length=80),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='type',
            field=models.CharField(choices=[('password_changed', 'Password Changed'), ('password_reset_requested', 'Password Reset Requested'), ('appointment_created', 'Appointment Created'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_rescheduled', 'Appointment Rescheduled'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_completed', 'Appointment Completed'), ('appointment_no_show', 'Appointment No Show'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('refund_success', 'Refund Success'), ('chat_message_received', 'Chat Message Received')], max_length=80),
        ),
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_id', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_6cf42c_idx')],
            },
        ),
    ]
